// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB04Tp_Ig1o4VbgJk06hi_UsdtWD0eVoJo',
    appId: '1:176970143348:web:c67828fe41e85754856321',
    messagingSenderId: '176970143348',
    projectId: 'device-streaming-f5775762',
    authDomain: 'device-streaming-f5775762.firebaseapp.com',
    storageBucket: 'device-streaming-f5775762.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQgEkDmMYT7HAFZ48UhANzf535JxYiC94',
    appId: '1:176970143348:android:86affec3d76b441f856321',
    messagingSenderId: '176970143348',
    projectId: 'device-streaming-f5775762',
    storageBucket: 'device-streaming-f5775762.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt-7ixWGznS3FLDkImx0g89rliAHQpdH4',
    appId: '1:176970143348:ios:55c82a91364b14d7856321',
    messagingSenderId: '176970143348',
    projectId: 'device-streaming-f5775762',
    storageBucket: 'device-streaming-f5775762.firebasestorage.app',
    iosBundleId: 'com.example.tradeAppNewClean',
  );
}
